version: "3.8"
services:
  e_commerce_db:
    image: mysql:8.0
    container_name: mysql_e_commerce
    restart: always
    environment:
      - MYSQL_DATABASE=e_commerce_db
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=saber
      # You can use whatever password you like
      - MYSQL_PASSWORD=montassar
      # Password for root access
      - MYSQL_ROOT_PASSWORD=montassar
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
  zipkin:
    image: openzipkin/zipkin:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
  redis:
    image: redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  
  service-registry:
    image: samotek/service-registry:0.0.1
    container_name: service-registry
    ports:
      - '8761:8761'
      
  config-server:
    image: samotek/config-server:0.0.1
    container_name: config-server
    environment:
      - EUREKA_SERVER_URL=service-registry
    ports:
      - '9296:9296'
    depends_on:
      - service-registry
      
  cloud-gateway:
    image: samotek/cloud-gateway:0.0.1
    container_name: cloud-gateway
    environment:
      - EUREKA_SERVER_URL=service-registry
      - CONFIG_SERVER_URL=config-server
    ports:
      - '9090:9090'
    depends_on:
      - config-server

# Names our volume
volumes:
  db:
    driver: local
  redis_data:
    driver: local