version: "3.8"
services:
  e_commerce_db:
    image: mysql:8.0
    container_name: mysql_e_commerce
    restart: always
    environment:
      - MYSQL_DATABASE=e_commerce_db
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=saber
      # You can use whatever password you like
      - MYSQL_PASSWORD=montassar
      # Password for root access
      - MYSQL_ROOT_PASSWORD=montassar
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
# Names our volume
volumes:
  db:
    driver: local