apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: samotek/order-service:0.0.1
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8082
        env:
          - name: EUREKA_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: eureka_server_url
                name: eureka-cm
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_server_url
                name: config-srv-cm
          - name: DB_HOSTNAME
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: mysql-cm

---

apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  type: LoadBalancer
  selector:
    app: order-service-app
  ports:
  - port: 80
    targetPort: 8082
    