apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: redis:7.0
        ports:
        - containerPort: 6379
          name: redis
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
        # env:
        #   - name: ALLOW_EMPTY_PASSWORD 
        #     value: yes
        #   - name: REDIS_DISABLE_COMMANDS 
        #     value: FLUSHDB,FLUSHALL

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-app
  ports:
  - port: 6379
    targetPort: 6379
