server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: montassar
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
okta:
  oauth2:
    issuer: https://dev-09346852.okta.com/oauth2/default
    audience: api://default
#eureka registry service config
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#  instance:
#    prefer-ip-address: true

