server:
  port: 9296
spring:
  application:
    name: CONFIG_SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///opt/external-config.yml
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka
